# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-16 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_businessunit_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businessunit',
            options={'verbose_name_plural': '业务线'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'verbose_name_plural': '服务器'},
        ),
        migrations.AddField(
            model_name='server',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='businessunit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repository.UserProfile', verbose_name='管理者'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='capacity',
            field=models.FloatField(verbose_name='磁盘容量(G)'),
        ),
    ]
