# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-16 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20180316_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='shab',
            field=models.CharField(default='123', max_length=32, verbose_name='版本'),
        ),
    ]
