# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-16 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_server_shab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='shab',
        ),
    ]
