# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-16 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_remove_server_shab'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='上次修改时间'),
        ),
    ]
